version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wg-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-np84hbax4sws"
s3_prefix = "wg-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
