AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda_wg_up_and_down

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.8
    Timeout: 3

Resources:
  WgUp:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: wg_up/
      Role: arn:aws:iam::914509945835:role/service-role/run_wireguard_stack-role-nwqm57n7
      Events:
        Api:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /wgup
            Method: get
            RestApiId:
              Ref: Api

  WgDown:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: wg_down/
      Role: arn:aws:iam::914509945835:role/service-role/run_wireguard_stack-role-nwqm57n7
      Events:
        Api:
          Type: Api
          Properties:
            Path: /wgdown
            Method: get
            RestApiId:
              Ref: Api

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      Domain:
        DomainName: wg.akawsdev.xyz
        CertificateArn: arn:aws:acm:us-east-1:914509945835:certificate/55dc7fd9-8ce4-496a-a6a0-fcc0260d530d
        Route53:
          HostedZoneId: Z08360562PFG1GR8FNX7E
          DistributionDomainName: wg
